logging:
  config: config/logback.xml

server:
  port: 8888
  ssl:
    enabled: true
    #client-auth: need
    key-alias: springconfigserver
    key-store: config/keystore/spring-config-server.p12
    key-store-type: PKCS12
    #key-password: 
    key-store-password: ENC(WxLUmL+yI3IsejD5pTRxrdE+4/lO648KgUaopb5RQSx4fWa1i31Hrsa2u+kYQIA5)
    #trust-store: config/keystore/spring-config-server.p12
    #trust-store-password: 
    #trust-store-type: PKCS12
spring:
  cloud:
    config:
      server:
        git:
          uri: ENC(nKyxf1ufcIP3Ngb6V/i+DK1PxZVzteRZbwwwgUTepBFk0vOon6yQYayO8BAB+osaXQWXA/4QG75Lr2d0hY3U9+WFJrM02qT+99zfUrVzpMzgXROaNCylEqx3dFGTm3vu)
          default-label: develop
          searchPaths: 
           - vocabulary-api
           - recipe-api
          clone-on-start: true
          force-pull: true
          strictHostKeyChecking: false
          # Get from ~/.ssh/known_hosts
          #hostKey: xxx
          #hostKeyAlgorithm: ssh-rsa
          ignore-local-ssh-settings: true
          # https://stackoverflow.com/questions/47024826/spring-cloud-config-server-using-ssh-key-for-git-and-running-in-docker
          private-key: ${SSH_KEY}